# Generated by Django 3.1.7 on 2021-06-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('s', 'Eslah_Talab'), ('o', 'Osol_Gera'), ('e', 'Etedali'), ('n', 'None')], max_length=1),
        ),
    ]
